#!/bin/bash
echo "======================================"
echo "STEP 0: PACKAGE CYCLES AND BOUNDARIES"
echo "======================================"
pnpm ls -r --depth -1
echo ""
echo "Finding forbidden cross-package imports (e.g. from dist, out of order):"
grep -r "from '.*@harness/" packages/*/src | grep -v "test.ts"
echo ""
echo "Finding concrete provider instantiations inside core code:"
grep -r -E "new Qdrant|new Anthropic|spawn\(|new MCPClient" packages/*/src | grep -v "test"
echo ""
echo "======================================"
echo "STEP 5: GLOBAL STATE AUDIT"
echo "======================================"
echo "Finding global variables, static state, module-level lets:"
grep -r -E "^let |^var |static [a-zA-Z0-9_]+ =" packages/*/src | grep -v "test"
echo ""
echo "======================================"
echo "STEP 10 & 11: TIMEOUTS & ABORT SIGNALS"
echo "======================================"
echo "Finding fetch, spawn, exec without timeout or signal:"
grep -r -E "fetch\(|spawn\(|exec\(" packages/*/src | grep -v "test"
echo ""
echo "======================================"
echo "STEP 8: ERRORS"
echo "======================================"
echo "Finding generic Error throws:"
grep -r "throw new Error" packages/*/src | grep -v "test"
echo ""
echo "======================================"
echo "STEP 14: EVENTS"
echo "======================================"
echo "Inspecting event schemas and writes:"
grep -r "fs.append" packages/events/src
echo ""
echo "======================================"
echo "STEP 36: SANDBOX"
echo "======================================"
echo "Inspecting SandboxRunner internals:"
cat packages/sandbox/src/runner.ts
cat packages/sandbox/src/worker.ts
echo ""
